name: XPBank
version: '1.1.0'
main: de.silentesc.xpbank.Main
api-version: '1.21'
authors: [ silentesc ]
description: A simple 1.21.4 Spigot Plugin where you can deposit your xp levels into your bank and send them to other players.

commands:
  xpbank_reloadcfg:
    description: Reloads the config
    usage: xpbank_reloadcfg
    permission: xpbank.reload
  bank:
    description: Everything related to deposit, withdraw, transfer or just show the xp points.
    usage: bank

permissions:
  xpbank.reload:
    description: Permission to use /xpbank_reloadcfg
    default: op
